/**
 * The scheduling engine.
 *
 * Pure, framework-free TypeScript. Nothing in this directory imports React, the
 * network, Supabase or the DOM — enforced three ways:
 *
 *   1. tsconfig.engine.json omits the DOM lib, so `window`/`fetch`/`localStorage`
 *      are compile errors here, not merely discouraged.
 *   2. eslint.config.js bans the imports outright.
 *   3. The `engine` Vitest project runs in a DOM-less node environment.
 *
 * Everything is deterministic. Where randomness is needed (draws), it comes from
 * a seeded PRNG whose seed is persisted on the tournament, so a bracket can be
 * regenerated byte-for-byte and an organiser can defend it when challenged.
 */

// Domain types
export type {
  BracketSide,
  Fixture,
  FixtureRound,
  GeneratedMatch,
  MatchCondition,
  MatchId,
  MatchResult,
  ParticipantId,
  PointsRules,
  Slot,
  StandingsRow,
  Tiebreaker,
} from './types'

export {
  DEFAULT_POINTS,
  DEFAULT_TIEBREAKERS,
  EngineError,
  byeSlot,
  groupPosition,
  loserOf,
  participantSlot,
  winnerOf,
} from './types'

// Determinism
export { createRng, shuffle, type Rng } from './rng'

// Seeding
export { bracketSize, knockoutRoundLabel, orderBySeed, seedOrder } from './seeding'

// Formats
export {
  generateRoundRobin,
  roundRobinMatchCount,
  roundRobinRoundCount,
  type RoundRobinOptions,
} from './roundRobin'

export {
  buildKnockoutBracket,
  generateSingleElimination,
  singleEliminationMatchCount,
  type SingleEliminationOptions,
} from './singleElimination'

export {
  doubleEliminationMatchCount,
  generateDoubleElimination,
  type DoubleEliminationOptions,
} from './doubleElimination'

export {
  assignGroups,
  generateGroupsToKnockout,
  groupLabel,
  resolveGroupQualifiers,
  resolveGroupSlot,
  seedQualifierSlots,
  type Group,
  type GroupStageFixture,
  type GroupStageOptions,
} from './groups'

export {
  maxSwissRounds,
  pairSwissRound,
  playedPairs,
  suggestedSwissRounds,
  type SwissPairingOptions,
  type SwissRound,
} from './swiss'

// Results and standings
export {
  bracketChampion,
  countLosses,
  isMatchPlayed,
  orderForResolution,
  propagateByes,
  resolveSlot,
  simulateBracket,
  type MatchOutcome,
  type OutcomeMap,
} from './resolve'

export { computeStandings, topN, type StandingsOptions } from './standings'

// Court and time-slot allocation
export {
  allocateCourts,
  computeWaitMinutes,
  findScheduleConflicts,
  minimumSlots,
  type AllocationOptions,
  type Court,
  type Schedule,
  type ScheduledMatch,
} from './allocation'
